[package]
name = "lqos_node_manager2"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1", features = [ "full", "parking_lot" ] }
log = "0"
tower-http = { version = "0.5.2", features = ["fs"] }
